#!/usr/bin/env python3

SINK_TYPE_DICT = {
    0: 'ECHO_SINK_BODY_SECTION',
    1: 'ECHO_SINK_SINGLE_QUOTE_ATTR_VAL',
    2: 'ECHO_SINK_DOUBLE_QUOTE_ATTR_VAL',
    3: 'ECHO_SINK_DOUBLE_QUOTE_CSS_VAL',
    4: 'ECHO_SINK_SINGLE_QUOTE_ATTR_VAL',
    5: 'ECHO_SINK_SINGLE_QUOTE_ATTR_VAL',
    6: 'ECHO_SINK_DOUBLE_QUOTE_CSS_VAL',
    7: 'ECHO_SINK_NO_QUOTE_ATTR_VAL',
    8: 'ECHO_SINK_NO_QUOTE_ATTR_VAL',
    9: 'ECHO_SINK_SINGLE_QUOTE_JS_BLOCK',
    10: 'ECHO_SINK_DOUBLE_QUOTE_ATTR_VAL',
    11: 'ECHO_SINK_DOUBLE_QUOTE_EVENT_VAL',
    12: 'ECHO_SINK_SINGLE_QUOTE_CSS_VAL',
    13: 'ECHO_SINK_DOUBLE_QUOTE_JS_BLOCK',
    14: 'ECHO_SINK_HTML_TAG_NAME',
    15: 'ECHO_SINK_ATTR_NAME',
    16: 'ECHO_SINK_SINGLE_QUOTE_JS_BLOCK'
}
